# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/giuseppezynq/OpenSSD_AXI_2/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/constr_nvme.xdc

# XDC: /home/giuseppezynq/OpenSSD_AXI_2/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/pinmap_others.xdc

# Block Designs: bd/OpenSSD2/OpenSSD2.bd
# Block Designs: The module: 'OpenSSD2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/OpenSSD2/ip/OpenSSD2_processing_system7_0_0/OpenSSD2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_processing_system7_0_0 || ORIG_REF_NAME==OpenSSD2_processing_system7_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_1/OpenSSD2_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_1 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_2/OpenSSD2_axi_interconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_2 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_0/OpenSSD2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==OpenSSD2_axi_bram_ctrl_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_bram_1/OpenSSD2_axi_bram_ctrl_0_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==OpenSSD2_axi_bram_ctrl_0_bram_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_mem_intercon_1/OpenSSD2_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_mem_intercon_1 || ORIG_REF_NAME==OpenSSD2_axi_mem_intercon_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_1/OpenSSD2_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_dma_0_1 || ORIG_REF_NAME==OpenSSD2_axi_dma_0_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axis_data_fifo_0_2/OpenSSD2_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axis_data_fifo_0_2 || ORIG_REF_NAME==OpenSSD2_axis_data_fifo_0_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_mem_intercon_1_1/OpenSSD2_axi_mem_intercon_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_mem_intercon_1_1 || ORIG_REF_NAME==OpenSSD2_axi_mem_intercon_1_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_xbar_1/OpenSSD2_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_xbar_1 || ORIG_REF_NAME==OpenSSD2_xbar_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_xbar_2/OpenSSD2_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_xbar_2 || ORIG_REF_NAME==OpenSSD2_xbar_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/OpenSSD2_NVMeHostController4L_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_NVMeHostController4L_0_0 || ORIG_REF_NAME==OpenSSD2_NVMeHostController4L_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/src/pcie_7x_0_core_top/pcie_7x_0_core_top.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_core_top || ORIG_REF_NAME==pcie_7x_0_core_top}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_0/OpenSSD2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_0 || ORIG_REF_NAME==OpenSSD2_auto_pc_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_1/OpenSSD2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_1 || ORIG_REF_NAME==OpenSSD2_auto_pc_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_cc_0/OpenSSD2_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_0 || ORIG_REF_NAME==OpenSSD2_auto_cc_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_2/OpenSSD2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_2 || ORIG_REF_NAME==OpenSSD2_auto_pc_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_cc_1/OpenSSD2_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_1 || ORIG_REF_NAME==OpenSSD2_auto_cc_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_3/OpenSSD2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_3 || ORIG_REF_NAME==OpenSSD2_auto_pc_3}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_cc_2/OpenSSD2_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_2 || ORIG_REF_NAME==OpenSSD2_auto_cc_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_4/OpenSSD2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_4 || ORIG_REF_NAME==OpenSSD2_auto_pc_4}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_us_0/OpenSSD2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_0 || ORIG_REF_NAME==OpenSSD2_auto_us_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_us_1/OpenSSD2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_1 || ORIG_REF_NAME==OpenSSD2_auto_us_1}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_processing_system7_0_0/OpenSSD2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_processing_system7_0_0 || ORIG_REF_NAME==OpenSSD2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_0/OpenSSD2_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_bram_1/OpenSSD2_axi_bram_ctrl_0_bram_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_1/OpenSSD2_axi_dma_0_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_1/OpenSSD2_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_dma_0_1 || ORIG_REF_NAME==OpenSSD2_axi_dma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_1/OpenSSD2_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_dma_0_1 || ORIG_REF_NAME==OpenSSD2_axi_dma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_axis_data_fifo_0_2/OpenSSD2_axis_data_fifo_0_2_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_axis_data_fifo_0_2/OpenSSD2_axis_data_fifo_0_2/OpenSSD2_axis_data_fifo_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_axis_data_fifo_0_2 || ORIG_REF_NAME==OpenSSD2_axis_data_fifo_0_2}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_xbar_1/OpenSSD2_xbar_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_xbar_2/OpenSSD2_xbar_2_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/src/pcie_7x_0_core_top/source/pcie_7x_0_core_top-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_core_top || ORIG_REF_NAME==pcie_7x_0_core_top}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/src/pcie_7x_0_core_top/synth/pcie_7x_0_core_top_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_0/OpenSSD2_auto_pc_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_1/OpenSSD2_auto_pc_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_0/OpenSSD2_auto_cc_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_0/OpenSSD2_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_0 || ORIG_REF_NAME==OpenSSD2_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_2/OpenSSD2_auto_pc_2_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_1/OpenSSD2_auto_cc_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_1/OpenSSD2_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_1 || ORIG_REF_NAME==OpenSSD2_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_3/OpenSSD2_auto_pc_3_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_2/OpenSSD2_auto_cc_2_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_cc_2/OpenSSD2_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_cc_2 || ORIG_REF_NAME==OpenSSD2_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_4/OpenSSD2_auto_pc_4_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_0/OpenSSD2_auto_us_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_0/OpenSSD2_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_0 || ORIG_REF_NAME==OpenSSD2_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_1/OpenSSD2_auto_us_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_1/OpenSSD2_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_1 || ORIG_REF_NAME==OpenSSD2_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/OpenSSD2_ooc.xdc
