# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.cache/wt [current_project]
set_property parent.project_path /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.2 [current_project]
set_property ip_repo_paths /home/giuseppezynq/OpenSSD_ACC_V3_4L/IPRepo [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/OpenSSD2.bd
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_processing_system7_0_0/OpenSSD2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_0/OpenSSD2_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_axi_bram_ctrl_0_bram_1/OpenSSD2_axi_bram_ctrl_0_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_xbar_1/OpenSSD2_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_0/OpenSSD2_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_0/OpenSSD2_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_axi_dma_0_0/OpenSSD2_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_xbar_0/OpenSSD2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_1/OpenSSD2_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_1/OpenSSD2_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_1/OpenSSD2_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/src/pcie_7x_0_core_top/source/pcie_7x_0_core_top-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_NVMeHostController4L_0_0/src/pcie_7x_0_core_top/synth/pcie_7x_0_core_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_0/OpenSSD2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_1/OpenSSD2_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_ds_0/OpenSSD2_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_ds_0/OpenSSD2_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_2/OpenSSD2_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_3/OpenSSD2_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_cc_0/OpenSSD2_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_cc_0/OpenSSD2_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_4/OpenSSD2_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/ip/OpenSSD2_auto_pc_5/OpenSSD2_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/OpenSSD2_ooc.xdc]
set_property is_locked true [get_files /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/sources_1/bd/OpenSSD2/OpenSSD2.bd]

read_xdc /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/constr_nvme.xdc
set_property used_in_implementation false [get_files /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/constr_nvme.xdc]

read_xdc /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/pinmap_others.xdc
set_property used_in_implementation false [get_files /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/pinmap_others.xdc]
set_property processing_order LATE [get_files /home/giuseppezynq/OpenSSD_ACC_V3_4L/OpenSSD2_2Ch8Way-1.0.3/OpenSSD2.srcs/constrs_1/implementation/pinmap_others.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top OpenSSD2 -part xc7z045ffg900-2
write_checkpoint -noxdef OpenSSD2.dcp
catch { report_utilization -file OpenSSD2_utilization_synth.rpt -pb OpenSSD2_utilization_synth.pb }
