webtalk_init -webtalk_dir /home/giuseppezynq/Accelerator_v3_testvectors/Accelerator_testbench_verilog/Accelerator_testbench_verilog.sim/sim_1/behav/xsim.dir/Accelerator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 14 11:24:26 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1494164" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111462_174111463_210709702_568" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0974cc81866b5ad19293a04cb72327a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c24e4954077e484fa1bf13a0298100f8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3454.851 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.85_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "279500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2512659461 -regid "174111462_174111463_210709702_568" -xml /home/giuseppezynq/Accelerator_v3_testvectors/Accelerator_testbench_verilog/Accelerator_testbench_verilog.sim/sim_1/behav/xsim.dir/Accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/giuseppezynq/Accelerator_v3_testvectors/Accelerator_testbench_verilog/Accelerator_testbench_verilog.sim/sim_1/behav/xsim.dir/Accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/giuseppezynq/Accelerator_v3_testvectors/Accelerator_testbench_verilog/Accelerator_testbench_verilog.sim/sim_1/behav/xsim.dir/Accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
